# Generated by Django 3.2.16 on 2022-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('booktitle', models.CharField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('genre', models.CharField(blank=True, max_length=500)),
                ('review', models.PositiveIntegerField()),
                ('favorite', models.BooleanField()),
            ],
        ),
    ]
